import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Jua } from 'next/font/google'
import styles from '@/styles/Home.module.sass'
import cn from 'classnames';

import { Logo } from '../../components/Logo';

import menu from '../styles/asstes/menu-burger.png';
import arrow from '../styles/asstes/angle-right.png';
import img from '../styles/asstes/Screenshot from 2023-04-03 12-34-00.png';
import heart from '../styles/asstes/heart.png';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const categoryArrey = [
    {
      name: 'Sport',
    },
    {
      name: 'News',
    }
  ]

  const itemsArrey = [
    {
      title: 'Dawid Kubacki: Płakaliśmy razem z Martą. Od razu napisałem do Anże...',
      img: {img}
    },
    {
      title: 'Dawid Kubacki: Płakaliśmy razem z Martą. Od razu napisałem do Anże...',
      img: {img}
    },
    {
      title: 'Dawid Kubacki: Płakaliśmy razem z Martą. Od razu napisałem do Anże...',
      img: {img}
    },
    {
      title: 'Dawid Kubacki: Płakaliśmy razem z Martą. Od razu napisałem do Anże...',
      img: {img}
    },
    {
      title: 'Dawid Kubacki: Płakaliśmy razem z Martą. Od razu napisałem do Anże...',
      img: {img}
    },
  ]

  const CategoryGenerator = (props) => {

    const ListGenerator = (props) => {
      return (
        <div className={styles.articleContainer}>
            <div className={styles.articleTop}>
              <div className={styles.reactionsWrapper}>
                <div className={styles.heartContainer}>
                  <Image
                    src={heart}
                    width={60}
                    height={57}
                    alt='heart IMG'
                    priority
                    className={styles.heartImg}
                  />
                </div>
                <div className={styles.reactionCounter}>
                  1,2 k
                </div>
              </div>
              <span className={styles.targetHTML}>
                onet.pl
              </span>
            </div>
          <div className={styles.headerContainer}>
            <h1 className={styles.articleHeader}>{props.box}</h1>
          </div>
          <Image
            src={img}
            width={450}
            height={250}
            alt='Article IMG'
            priority
            className={styles.articleImg}
          />
        </div>
      )
    }

   const ItemsList = itemsArrey.map((item, index) => <ListGenerator box={item.title}/>)

    return (
      <>
        <div className={styles.categoryHeader}>
        <h1 className={inter.className}>{props.item}</h1>
          <Image
            src={arrow}
            width={20}
            height={20}
            alt='arrow IMG'
            className={styles.arrowImg}
          />
        </div>
        <div className={styles.itemsList}>
          {ItemsList}
        </div>
      </>
    )
  }

  const CategoryList = categoryArrey.map( item => <CategoryGenerator item={item.name} />)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navbarContainer}>
        <nav className={styles.navbar}>
          <Logo/>
          <span className={styles.menuContainer}>
            <Image
              src={menu}
              width={30}
              height={30}
              alt='Menu IMG'
              priority
              className={styles.menuImg}
            />
          </span>
        </nav>
      </div>
      <main className={styles.main}>
        <div className={styles.mainContainer}>
          {CategoryList}
        </div>
      </main>
    </>
  )
}
